// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using meetup_telegram_bot.Infrastructure;

#nullable disable

namespace meetup_telegram_bot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220331132120_AddGeneralQ")]
    partial class AddGeneralQ
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("meetup_telegram_bot.Data.DbEntities.FeedbackDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("FutureProposal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralFeedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks", (string)null);
                });

            modelBuilder.Entity("meetup_telegram_bot.Data.DbEntities.PresentationDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisplayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SpeackerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Presentations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ddddcfc4-9a9d-4277-9b34-23c195468113"),
                            Description = "Описание",
                            IsDisplayed = false,
                            SpeackerName = "Hanna",
                            Title = "Путь разработчика"
                        },
                        new
                        {
                            Id = new Guid("03f626a6-3d04-4ffd-8dbb-f0ba307830c5"),
                            Description = "Описание",
                            IsDisplayed = false,
                            SpeackerName = "Kseniya",
                            Title = "In-live разработка"
                        },
                        new
                        {
                            Id = new Guid("46ff2291-6111-4dbf-a3e9-23d2c9e1ad7d"),
                            Description = "Описание",
                            IsDisplayed = false,
                            SpeackerName = "Сюрприз",
                            Title = "Третий доклад"
                        },
                        new
                        {
                            Id = new Guid("fadabc27-40e4-47f3-bc1b-f0916b4772cd"),
                            Description = "Описание",
                            IsDisplayed = true,
                            SpeackerName = "Hanna",
                            Title = "Базы данных. То, что вы РЕАЛЬНО будете использовать на проекте"
                        },
                        new
                        {
                            Id = new Guid("0c03ba0b-3b46-42ba-ba39-6b635c9a4bc0"),
                            Description = "Описание",
                            IsDisplayed = true,
                            SpeackerName = "Kseniya",
                            Title = "REST-архитектура или как усидеть на 6 стулья"
                        },
                        new
                        {
                            Id = new Guid("99d09f48-0fec-4ef4-8292-2bab81de8d37"),
                            Description = "Описание",
                            IsDisplayed = true,
                            SpeackerName = "Илья",
                            Title = "Реалии фуллстека"
                        },
                        new
                        {
                            Id = new Guid("958ae825-56f4-4390-90e3-4aa9741673a3"),
                            Description = "Описание",
                            IsDisplayed = true,
                            SpeackerName = "",
                            Title = "Вопрос не по темам"
                        });
                });

            modelBuilder.Entity("meetup_telegram_bot.Data.DbEntities.QuestionDbEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("PresentationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PresentationId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("meetup_telegram_bot.Data.DbEntities.QuestionDbEntity", b =>
                {
                    b.HasOne("meetup_telegram_bot.Data.DbEntities.PresentationDbEntity", null)
                        .WithMany()
                        .HasForeignKey("PresentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
